购物车/aixianfeng/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.static import serve
from usr import views
from aixianfeng import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usr/',include('usr.urls',namespace='axf')),
    # url(r'static/(?P<path>.*)$',serve, {"document_root":settings.STATIC_ROOT}),
    # url(r'^$',views.home)
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

购物车/usr/urls.py
from django.conf.urls import url
from usr import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^market/$', views.market, name='market'),
    url(r'^smarketpragram/(\d+)/(\d+)/(\d+)/', views.marketpragram, name='smarketpragram'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register,name='register'),
    url(r'^login/', views.login,name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^addgoods/',views.addgoods,name='addgoods'),
    url(r'^subgoods/',views.subgoods,name='subgoods'),
    url(r'^goodsel/$',views.select_goods,name='goodsel'),
    url(r'^ordergoods/',views.ordergoods,name='ordergoods'),
    url(r'^user_orderinfo/(\d+)',views.user_orderinfo,name='user_orderinfo'),
    url(r'^change_order_status/(\d+)',views.change_order_status,name='change_order_status'),
    url(r'^user_wait_pay/$',views.user_wait_pay,name='user_wait_pay'),
    url(r'^user_pay/$',views.user_pay,name='user_pay'),
    url(r'^allselt/$',views.allSelectChange,name='allselt')




]

购物车/usr/models.py
from django.db import models


# Create your models here.


class Main(models.Model):
    img = models.CharField(max_length=200)  # 图片
    name = models.CharField(max_length=100)  # 名称
    trackid = models.CharField(max_length=16)  # 通用ID

    class Meta:
        abstract = True


class MainWheel(Main):
    # 轮播banner
    class Meta:
        db_table = 'axf_wheel'


class MainNav(Main):
    # 导航
    class Meta:
        db_table = 'axf_nav'


class MainMustBuy(Main):
    # 必购
    class Meta:
        db_table = 'axf_mustbuy'


class MainShop(Main):
    # 商店
    class Meta:
        db_table = 'axf_shop'


class MainShow(Main):
    categoryid = models.CharField(max_length=16)
    brandname = models.CharField(max_length=100)
    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)
    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)
    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'


# 闪购
class FootType(models.Model):
    typeid = models.CharField(max_length=16)
    typename = models.CharField(max_length=100)
    childtypename = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    productid = models.CharField(max_length=16)  # 商品ID
    productimg = models.CharField(max_length=200)  # 商品图片
    productname = models.CharField(max_length=100)  # 商品名称
    productlongname = models.CharField(max_length=200)  # 商品的具体规格
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)  # 商品重量
    price = models.FloatField(default=0)  # 折后价格
    marketprice = models.FloatField(default=1)  # 原价
    categoryid = models.CharField(max_length=16)  # 分类ID
    childcid = models.CharField(max_length=16)  # 子分类ID
    childcidname = models.CharField(max_length=100)  # 子分类名称
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)  # 排序
    productnum = models.IntegerField(default=1)  # 销量排序

    class Meta:
        db_table = 'axf_goods'


# 用户表
class UserModel(models.Model):
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=64, unique=True)
    sex = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='icons')  # 头像
    is_delete = models.BooleanField(default=False)  # 是否删除

    class Meta:
        db_table = 'axf_users'


# 购物车
class CartModel(models.Model):
    user = models.ForeignKey(UserModel)  # 关联用户
    goods = models.ForeignKey(Goods)  # 关联商品
    c_num = models.IntegerField(default=1)  # 商品个数
    is_select = models.BooleanField(default=True)  # 是否选择商品

    class Meta:
        db_table = 'axf_cart'


# 订单
class OrderModel(models.Model):
    user = models.ForeignKey(UserModel)
    o_num = models.CharField(max_length=64)
    # 0 代表已下单，但是未付款， 1 已付款未发货  2  已付款
    o_status = models.IntegerField(default=0)
    o_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'axf_order'


# 订单商品详情
class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(Goods)
    order = models.ForeignKey(OrderModel)
    goods_num = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_order_goods'


class UserTicketModel(models.Model):
    u_user = models.ForeignKey(UserModel)
    ticket = models.CharField(max_length=30, null=True)
    ticket_out_time = models.DateTimeField()

    class Meta:
        db_table = 'axf_user_ticket'

购物车/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">

    <!--订单编号-->
    <h3>订单编号:{{ order_id }}</h3>
    <!--处理结束-->
    <ul>

        <!--所有订单信息展示-->
        {% for good in order_goods.ordergoodsmodel_set.all %}
            <li>
                <!--商品名称展示-->
                <img src="{{ good.goods.productimg }}">
                <label>{{ good.goods.productlongname }}</label>

                <span> <!-- 数量展示 -->数量：{{ good.goods_num }}</span>
            </li>

        <!--订单处理结束-->
        {% endfor %}
    </ul>
        <!--订单id展示-->

        <a href="{% url 'axf:change_order_status' order_id %}"><button id="alipay" class="btn btn-success btn-block" orderid="">Alipay</button></a>

    </div>


{% endblock %}

购物车/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>
    <div style="height:4px;width:100%; border: 1px solid red"></div>
    <ul>
        <!--订单展示-->
        {% for order in orders %}
            <li>
                <a href="#">
                    <p><!-- 订单id -->订单编号：{{ order.id }}</p>
                    {% for goods in order.ordergoodsmodel_set.all %}
                    <p><!-- 数量 -->商品数量：{{ goods.goods_num }}</p>
                        <!--展示商品的名称-->
                        商品名称：{{ goods.goods.productlongname }}
                        <li>
                            <img src="{{ goods.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->
                        <div style="height:4px;width:100%; border: 1px solid red"></div>
                        {% endfor %}
                </a>
            </li>
        <!--订单处理结束-->
        {% endfor %}
    </ul>


{% endblock %}

购物车/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>
    <div style="height:4px;width:100%; border: 1px solid red"></div>

    <ul>
        <!--订单信息展示-->
        {% for order in orders %}
            <li>
                <a href="{% url 'axf:user_orderinfo' order.id %}">
                    <p><!-- 订单id -->订单编号：{{ order.id }}</p>
                    {% for good in order.ordergoodsmodel_set.all %}
                        <p><!-- 数量 -->商品数量：{{ good.goods_num }}</p>
                        <!--展示商品的名称-->商品名称：{{ good.goods.productlongname }}
                        <li>
                            <img src="{{ good.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->
                        <div style="height:4px;width:100%; border: 1px solid red"></div>
                    {% endfor %}
            </a>
            </li>
            <!--订单处理结束-->
        {% endfor %}

    </ul>


{% endblock %}