购物车/aixianfeng/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.static import serve
from usr import views
from aixianfeng import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usr/',include('usr.urls',namespace='axf')),
    # url(r'static/(?P<path>.*)$',serve, {"document_root":settings.STATIC_ROOT}),
    # url(r'^$',views.home)
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

购物车/usr/urls.py
from django.conf.urls import url
from usr import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^market/$', views.market, name='market'),
    url(r'^smarketpragram/(\d+)/(\d+)/(\d+)/', views.marketpragram, name='smarketpragram'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register,name='register'),
    url(r'^login/', views.login,name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^addgoods/',views.addgoods,name='addgoods'),
    url(r'^subgoods/',views.subgoods,name='subgoods'),
    url(r'^goodsel/$',views.select_goods,name='goodsel'),
    url(r'^ordergoods/',views.ordergoods,name='ordergoods'),
    url(r'^user_orderinfo/(\d+)',views.user_orderinfo,name='user_orderinfo'),
    url(r'^change_order_status/(\d+)',views.change_order_status,name='change_order_status'),
    url(r'^user_wait_pay/$',views.user_wait_pay,name='user_wait_pay'),
    url(r'^user_pay/$',views.user_pay,name='user_pay'),
    url(r'^allselt/$',views.allSelectChange,name='allselt')




]

购物车/templates/cart/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/comm.js' %}"></script>
{% endblock %}


{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <div class="full">

            <section class="clear">

                <ul>
                    <li>收货人:王帅帅
                        <div><p><span><a href="#">修改&gt;</a></span></p></div>
                    </li>
                    <li>电话:8008208820</li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>

                </ul>


                <div class="bill">

                    <p>闪送超市</p>

                    <a href="#">凑单专区</a>

                    <p>满100减99</p>

                </div>

                <p class="delivery">

                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>

                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>


                <menu>

                    <ul>
                        <!--购物车信息展示-->
                        {% for cart in carts %}
                            <li class="menuList">
                                <div class="confirm">
                                    {% csrf_token %}
                                    <span id="checkgoods_{{ cart.id }}">
                                        {% if cart.is_select %}
                                            <span onclick="selectGoods({{ cart.id }})">√</span>
                                        {% else %}
                                            <span onclick="selectGoods({{ cart.id }})">X</span>
                                        {% endif %}

                                    </span>
                                </div>
                                <a href="#">
                                    <img src="{{ cart.goods.productimg }}" alt="">
                                    <p>{{ cart.goods.productlongname }}</p>
                                    <p>￥:<span id="price">{{ cart.goods.price }}</span></p>
                                </a>
                                <section>
                                    {% csrf_token %}
                                    <button onclick="subshop({{ cart.goods.id }})">-</button>
                                    <span id="num_{{ cart.goods.id }}">{{ cart.c_num }}</span>
                                    <button onclick="addshop({{ cart.goods.id }})">+</button>
                                </section>
                            </li>
                            <!--购物车数据处理结束-->
                        {% endfor %}

                        <li class="payTheBill">

                            {% csrf_token %}
                            <div class="confirm">
                                <span id="changesel">
                                    {% if all_select %}
                                        <span onclick="allSelectChange(1)">√</span>
                                    {% else %}
                                        <span onclick="allSelectChange(0)">X</span>
                                    {% endif %}
                                </span>
                            </div>

                            <p>
                                <span>全选</span>
                            <span id="sum">{{ total }}</span>
                            </p>

                            <span><a href="{% url 'axf:ordergoods' %}">下单</a></span>


                        </li>

                    </ul>

                </menu>

                {#            <div class="menuList">#}
                {##}
                {#                {% for cart in carts %}#}
                {##}
                {#                    <div class="confirm">#}
                {#                    <span>#}
                {#                        <span>√</span>#}
                {#                    </span>#}
                {#                    </div>#}
                {##}
                {#                    <a href="#">#}
                {#                        <img src="{{ cart.goods.productimg }}" alt="{{ cart.goods.productlongname }}">#}
                {#                        <p>{{ cart.goods.productlongname }}</p>#}
                {#                    </a>#}
                {##}
                {#                {% endfor %}#}
                {##}
                {##}
                {#            </div>#}
            </section>


        </div>


    </div>


{% endblock %}